---
kind: pipeline
name: test-1-16

steps:
  - name: test
    image: golang:1.16
    commands:
      - export GO111MODULE=on
      - go version
      - go test ./...

---
kind: pipeline
name: test-1-17

steps:
  - name: test
    image: golang:1.17
    commands:
      - export GO111MODULE=on
      - go version
      - go test ./...

...